cmake_minimum_required(VERSION 3.25)
project(check_deps)
find_package(ZLIB)
if(ZLIB_FOUND)
    message(STATUS "Found ZLIB: ${ZLIB_VERSION}")
endif()

find_package(PkgConfig)
pkg_check_modules(LZ4 liblz4)
if(LZ4_FOUND)
    message(STATUS "Found LZ4: ${LZ4_VERSION}")
endif()
